apiVersion: v1
kind: Pod
metadata:
        name: example
spec:
        containers:
                - name: web
                  image: nginx:latest
                  imagePullPolicy: Never
                  - name: django
                  image: django:latest
                  imagePullPolicy: IfNotPresent
                  imagePullPolicy: Never
                  command: ["echo", "hello"]
